inherit_from:
  - https://shopify.github.io/ruby-style-guide/rubocop.yml

AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - gemfiles/vendor/**/*

Style/MethodCallWithArgsParentheses:
  Exclude:
    - Gemfile
    - gemfiles/*
