sudo: false
cache: bundler
language: ruby
before_install:
  - gem update bundler
rvm:
  - 2.5
  - 2.6
  - 2.7
gemfile:
  - gemfiles/activesupport_5.2.gemfile
  - gemfiles/activesupport_6.0.gemfile
script:
  - bundle exec rubocop --config .rubocop.yml
  - bundle exec rake test
  - bundle exec rspec
notifications:
  email: false
