sudo: false
cache: bundler
language: ruby
before_install:
  - gem update bundler
rvm:
  - 2.3
  - 2.4
  - 2.5
gemfile:
  - gemfiles/activesupport_5.0.gemfile
  - gemfiles/activesupport_5.1.gemfile
  - gemfiles/activesupport_5.2.gemfile
notifications:
  email: false
