sudo: false
cache: bundler
language: ruby
before_install:
  - gem update bundler
rvm:
  - 2.3
  - 2.4
  - 2.5
gemfile:
  - gemfiles/activesupport_4.2.gemfile
  - gemfiles/activesupport_5.0.gemfile
  - gemfiles/activesupport_5.1.gemfile
  - gemfiles/activesupport_5.2.gemfile
script:
  - bundle exec rubocop --config .rubocop.yml
  - bundle exec rake test
  - bundle exec rspec
notifications:
  email: false
